model_list:
  - model_name: claude-3-haiku-proxy
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
      aws_region_name: os.environ/AWS_REGION
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY


litellm_settings:
  set_verbose: True 

general_settings:
  port: 4000
  host: 0.0.0.0